#!/usr/bin/env python3
"""
Generate game_links table SQL
==============================
Reads:
  - ufa_youtube_links.xlsx   → YT_highlights (HIGH confidence only)
  - ufa_watchufa_links.xlsx  → WatchUFA_full (all matched games)

Outputs:
  - game_links.sql  — CREATE TABLE + INSERT for all games
"""

import openpyxl

YOUTUBE_XLSX  = "ufa_youtube_links.xlsx"
WATCHUFA_XLSX = "ufa_watchufa_links.xlsx"
OUTPUT_SQL    = "game_links.sql"


def read_youtube_links(path):
    """Returns {GameID: youtube_url} for HIGH confidence rows only."""
    wb = openpyxl.load_workbook(path)
    ws = wb["YouTube Links"]
    headers = [cell.value for cell in ws[1]]

    links = {}
    for row in ws.iter_rows(min_row=2, values_only=True):
        if not any(row):
            continue
        r = dict(zip(headers, row))
        if r.get("Confidence") == "HIGH" and r.get("YouTube URL"):
            links[r["GameID"]] = r["YouTube URL"]

    print(f"YouTube: {len(links)} HIGH-confidence links loaded.")
    return links


def read_watchufa_links(path):
    """Returns {GameID: watchufa_url} for all matched rows."""
    wb = openpyxl.load_workbook(path)
    ws = wb["WatchUFA Links"]
    headers = [cell.value for cell in ws[1]]

    links = {}
    for row in ws.iter_rows(min_row=2, values_only=True):
        if not any(row):
            continue
        r = dict(zip(headers, row))
        if r.get("WatchUFA URL"):
            links[r["GameID"]] = r["WatchUFA URL"]

    print(f"WatchUFA: {len(links)} links loaded.")
    return links


def read_all_game_ids(path):
    """Returns all GameIDs from the WatchUFA spreadsheet (covers all 155 games)."""
    wb = openpyxl.load_workbook(path)
    ws = wb["WatchUFA Links"]
    headers = [cell.value for cell in ws[1]]

    ids = []
    for row in ws.iter_rows(min_row=2, values_only=True):
        if not any(row):
            continue
        r = dict(zip(headers, row))
        if r.get("GameID"):
            ids.append(r["GameID"])
    return ids


def q(val):
    """Quote a value for SQL: NULL if empty, escaped string otherwise."""
    if not val:
        return "NULL"
    return "'" + str(val).replace("'", "''") + "'"


def write_sql(game_ids, yt_links, watchufa_links):
    lines = [
        "-- game_links table: GameID, YT_highlights, YT_full, WatchUFA_full",
        "-- Generated by generate_game_links_sql.py",
        "-- REVIEW before running!",
        "",
        "CREATE TABLE IF NOT EXISTS public.game_links (",
        '  "GameID"        text PRIMARY KEY,',
        '  "YT_highlights" text,',
        '  "YT_full"       text,',
        '  "WatchUFA_full" text',
        ");",
        "",
        "BEGIN;",
        "",
    ]

    for game_id in game_ids:
        yt  = yt_links.get(game_id)
        ufa = watchufa_links.get(game_id)
        lines.append(
            f"INSERT INTO public.game_links "
            f'("GameID", "YT_highlights", "YT_full", "WatchUFA_full") VALUES '
            f"({q(game_id)}, {q(yt)}, NULL, {q(ufa)})"
            f"\n  ON CONFLICT (\"GameID\") DO UPDATE SET"
            f'\n    "YT_highlights" = EXCLUDED."YT_highlights",'
            f'\n    "YT_full"       = EXCLUDED."YT_full",'
            f'\n    "WatchUFA_full" = EXCLUDED."WatchUFA_full";'
        )

    lines += ["", "COMMIT;"]

    with open(OUTPUT_SQL, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    yt_count  = sum(1 for g in game_ids if yt_links.get(g))
    ufa_count = sum(1 for g in game_ids if watchufa_links.get(g))
    print(f"SQL saved: {OUTPUT_SQL}")
    print(f"  {len(game_ids)} rows total")
    print(f"  {yt_count} with YT_highlights")
    print(f"  {ufa_count} with WatchUFA_full")


def main():
    yt_links       = read_youtube_links(YOUTUBE_XLSX)
    watchufa_links = read_watchufa_links(WATCHUFA_XLSX)
    game_ids       = read_all_game_ids(WATCHUFA_XLSX)
    write_sql(game_ids, yt_links, watchufa_links)


if __name__ == "__main__":
    main()
